INSERT INTO CASH_CARD(ID, AMOUNT, OWNER) VALUES (99, 123.45, 'sangram');
INSERT INTO CASH_CARD(ID, AMOUNT, OWNER) VALUES (100, 1.00, 'sangram');
INSERT INTO CASH_CARD(ID, AMOUNT, OWNER) VALUES (101, 150.00, 'sangram');
INSERT INTO CASH_CARD(ID, AMOUNT, OWNER) VALUES (102, 75.00, 'anushree');
INSERT INTO CASH_CARD(ID, AMOUNT, OWNER) VALUES (103, 98.00, 'anushree');
